language: node_js
node_js:
- "16.16.0"

install:
- npm install newman
- npm install -g newman-reporter-htmlextra

script:
- node_modules/.bin/newman run tests/SwaggerPetStore.postman_collection.json -e tests/PetStoreEnv.postman_environment.json --reporters cli,htmlextra-export reports/petStoreReport.html
