language: node_js
node_js:
- "18"

install:
- npm install newman
- npm install -g newman-reporter-htmlextra

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run SwaggerPetStore.postman_collection.json -e PetStoreEnv.postman_environment.json --reporters cli, htmlextra-export reports/petStoreReport.html
