language: node_js
node_js:
- "18.6.0"

install:
- npm install -g newman
- npm install -g newman-reporter-htmlextra

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run SwaggerPetStore-Postman/SwaggerPetStore.postman_collection.json -e SwaggerPetStore/PetStoreEnv.postman_environment.json
--reporters cli, htmlextra-export reports/petStoreReport.html
